import json
import logging
import re
from typing import Any

from app.services.provider_service import ProviderService

logger = logging.getLogger(__name__)


class EvaluatorService:
    """Service to evaluate generated output quality using an LLM-as-a-Judge routine."""

    def __init__(
        self, provider_service: ProviderService, gold_standard_model: str = "mistral-7b"
    ) -> None:
        """
        Initializes the evaluator with an LLM provider client and a benchmark model.

        Args:
            provider_service (ProviderService): Integrated LLM client provider.
            gold_standard_model (str): High-tier model to serve as the ground truth benchmark.
        """
        self.provider = provider_service
        self.gold_model = gold_standard_model
        logger.debug("Initialized EvaluatorService with benchmark model: %s", gold_standard_model)

    async def verify_quality_async(self, prompt: str, cheap_model_output: str) -> dict[str, Any]:
        """
        Compares cheap model output against a gold standard response using a judge model.

        Args:
            prompt (str): Original user prompt.
            cheap_model_output (str): Text generated by the routed model.

        Returns:
            Dict[str, Any]: A dictionary containing status, score, reasons, and flags.
        """
        # Step 1: Query benchmark gold standard model for ground truth response
        try:
            logger.info("Fetching ground truth from benchmark model: %s", self.gold_model)
            gold_response = await self.provider.send_request(prompt, self.gold_model)
            gold_text = gold_response.output_text
        except Exception as provider_err:
            logger.error("Failed to fetch response from benchmark model: %s", provider_err)
            return {
                "status": "EVAL_FAILED",
                "reason": f"Gold benchmark endpoint target down: {provider_err}",
                "quality_score": 0.0,
                "escalate_flag": True,
                "gold_cost_incurred": 0.0,
            }

        # Step 2: Formulate prompt for judge assessment (LLM-as-a-Judge)
        eval_prompt = f"""You are an expert Production AI Quality Audit Engine. Your task is to evaluate the quality of a CHEAP model's response against a high-tier GOLD STANDARD response.

    USER ORIGINAL PROMPT:
    \"\"\"{prompt}\"\"\"

    GOLD STANDARD RESPONSE (Ground Truth):
    \"\"\"{gold_text}\"\"\"

    CHEAP MODEL RESPONSE (Under Review):
    \"\"\"{cheap_model_output}\"\"\"

    Analyze factual alignment, accuracy, and completeness. You MUST respond strictly with a valid JSON block enclosed in markdown code fences, containing exactly two keys: 'score' (an integer from 0 to 100) and 'reason' (a short engineering explanation).

    Example Output Format:
    ```json
    {{
      "score": 90,
      "reason": "Captures the main architectural features perfectly, missing minor details."
    }}
    ```
    """
        # Step 3: Dispatch judge prompt and parse structured metrics
        eval_text = ""
        try:
            logger.info("Calling judge LLM for quality evaluation...")
            eval_response = await self.provider.send_request(eval_prompt, self.gold_model)
            eval_text = eval_response.output_text

            # Robust JSON extraction via regex pattern matching
            json_match = re.search(r"```json\s*(\{.*?\})\s*```", eval_text, re.DOTALL)

            if json_match:
                parsed_metrics = json.loads(json_match.group(1), strict=False)
            else:
                # Fallback: attempt to parse direct string if code fences are absent
                parsed_metrics = json.loads(eval_text.strip(), strict=False)

            score = float(parsed_metrics.get("score", 50.0))
            reason = parsed_metrics.get(
                "reason", "Fails to present structured logs format evaluation."
            )

            # Decision Matrix Rule: Escalate to human review if quality score is below 80%
            escalate_flag = score < 80.0
            logger.info("Evaluation completed. Score: %.1f, Escalate: %s", score, escalate_flag)

            return {
                "status": "SUCCESS",
                "quality_score": score,
                "reason": reason,
                "escalate_flag": escalate_flag,
                "gold_cost_incurred": gold_response.total_cost + eval_response.total_cost,
            }

        except Exception as eval_parse_err:
            logger.warning(
                "Failed to parse judge output: %s. Raw output: %s", eval_parse_err, eval_text
            )
            return {
                "status": "PARSING_ANOMALY",
                "reason": f"LLM-as-a-judge formatting deviation: {eval_parse_err}. Raw Text: {eval_text[:100]}",
                "quality_score": 0.0,
                "escalate_flag": True,
                "gold_cost_incurred": 0.0,
            }
