from pydantic import BaseModel, Field
from typing import Optional, Dict, Any  

class ModelResponse(BaseModel):
    provider: str = Field(..., description="The upstream cloud provider handled.")
    model_name: str = Field(..., description="System internal model name.")
    output_text: str = Field(..., description="The text generated by the model.")
    prompt_tokens: int = Field(..., description="Number of tokens calculated in prompt.")
    completion_tokens: int = Field(..., description="Number of tokens calculated in response.")
    total_cost: float = Field(..., description="Total processing transaction cost in USD ($).")
    latency_ms: float = Field(..., description="Network turn-around execution time.")